name       : python-sphinxcontrib-qthelp
version    : 1.0.3
release    : 4
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-qthelp/archive/1.0.3.tar.gz : 587eeff750c97570290122116cdd3522f6ff804e55d44281eefce30b22db5531
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for outputting QtHelp documents
description: |
    sphinxcontrib-qthelp is a sphinx extension which outputs QtHelp document.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
