name       : python-sphinxcontrib-qthelp
version    : 1.0.2
release    : 1
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-qthelp/archive/1.0.2.tar.gz : 3031114de426e28c979f5655555b5c7f5ece89266e542d4b6749c0a09d9919d7
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for outputting QtHelp documents
description: |
    sphinxcontrib-qthelp is a sphinx extension which outputs QtHelp document.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
